config/routes.rb
Rails.application.routes.draw do
  get 'chef/index'
  get 'chef/cook'

  devise_for :users, controllers: {
        sessions: 'users/sessions', 
        registrations: 'users/registrations'
      }

  get 'products/index'

  get 'products/new'

  get 'product_categories/index'

  get 'product_categories/new'

  get 'units/index'

  get 'units/new'

  authenticated :user do
    root to: 'chef#cook', as: :authenticated_root
  end
  root 'chef#index'

  resources :recipe_categories
  resources :recipes
  resources :units
  resources :product_categories
  resources :products do    
    collection do
      get 'autocomplete'
    end
  end 
  resources :storings

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :product_category
  belongs_to :category, class_name: :product_category, foreign_key: "product_category_id"
  belongs_to :unit
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :recipe_category
  belongs_to :category, class_name: :recipe_category, foreign_key: "recipe_category_id"
  has_many :ingredients
  has_many :products, through: :ingredients

  accepts_nested_attributes_for :ingredients
end

app/models/recipe_category.rb
class RecipeCategory < ActiveRecord::Base
end

app/models/storage.rb
class Storage < ActiveRecord::Base
	belongs_to :user
end

app/models/storing.rb
class Storing < ActiveRecord::Base
  belongs_to :storage
  belongs_to :product
end

app/models/unit.rb
class Unit < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :storages
end

app/controllers/chef_controller.rb
class ChefController < ApplicationController
  autocomplete :product, :name
  
  def index
  end

  def cook
  	@storing = Storing.new
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
  	@products = Product.all
  end

  def new
  	@product = Product.new
  	@categories = ProductCategory.all
  	@units = Unit.all
  end

  def create
  	@product = Product.new(params.require(:product).permit(:name))
  	@product.product_category = ProductCategory.find(params[:product][:category])
  	@product.unit = Unit.find(params[:product][:unit])
  	if @product.save
  		redirect_to products_path
  	else
  		render 'new'
  	end
  end

  def autocomplete
    @products = Product.order(:name).where("name LIKE ?", "%#{params[:term]}%")
    respond_to do |format|
      format.html
      format.json { 
        render json: @products.map(&:name)
      }
    end
  end



end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	def index
		@recipes = Recipe.all
	end

	def new
		@recipe = Recipe.new
		@recipe.ingredients.build
		@categories = RecipeCategory.all
		@products = Product.all
	end

	def create
		@recipe = Recipe.new(params.require(:recipe).permit(:title, :summary, :instructions))
		@recipe.recipe_category = RecipeCategory.find(params[:recipe][:category])

		if @recipe.save
			params[:recipe][:ingredient_ids].reject(&:blank?).each do |productId|
				@ingredient = Ingredient.new(recipe: @recipe, product: Product.find(productId), amount: 1)
				@ingredient.save
			end
			debugger
			redirect_to recipes_path
		else
			render 'new'
		end
	end
end

app/controllers/storings_controller.rb
class StoringsController < ApplicationController

	def new
		debugger
	end

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
	
  def index
  	@units = Unit.all
  end

  def new
  	@unit = Unit.new
  end

  def create
  	@unit = Unit.new(params.require(:unit).permit(:name))
  	if @unit.save
  		redirect_to units_path
  	else
  		render 'new'
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chef_helper.rb
module ChefHelper
end

app/helpers/product_categories_helper.rb
module ProductCategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/recipe_categories_helper.rb
module RecipeCategoriesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/storings_helper.rb
module StoringsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/chef/cook.html.erb
<div class="row cookContent">
	<div class="col-sm-8">
		<div class="recipes">
			<div class="recipesWrapper">
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			<p>recipes go here<p>
			</div>
		</div>
	</div>
	<div class="storage col-sm-4">
		<div class="col-sm-12">
			<%= form_tag new_storing_path, method: :get, remote: true, class: 'navbar-form navbar-left' do %>
			<div class="col-sm-10">
		   		<div class='form-group'>
		    		<%= text_field_tag :query, params[:query], id: "navbar-search-input", class: 'form-control', placeholder: 'Product name.....' %>
		   		</div>
		   	</div>
		   	<div class="col-sm-2">
		   		<%= button_tag(type: 'submit', id: 'navbar-search-btn', class: 'btn btn-default') do %>
		     		<span class='glyphicon glyphicon-plus'></span>
		   		<% end %>  
		   	</div>
			<% end %>
		</div>
	<p>storage go here</p>
	</div>
</div>

app/views/chef/index.html.erb
<div class="row">
	<div class="col-sm-5">
		<h1><span>CHEF</span><br>the next generation kitchen app</h1>
		<div class="features">
			<p>
				<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
				Keep track of your food storage.
			</p>
			<p>
				<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
				Get recipes instantly. No searching.
			</p>
			<p>
				<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
				Menage your diet and eat healthy.
			</p>
			<p>
				<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
				Register. It's free and always will be.
			</p>
		</div>
		<%= link_to 'Cook', new_user_session_path, remote: true, 
			class:"ctaBtn btn btn-primary col-sm-8 col-sm-offset-2 col-xs-12" %>
	</div>
	<div class="col-sm-7">
		<div class="video"><%= image_tag('video.png', width: "100%") %></div>
	</div>
</div>